### ISSUE TITLE
No output through usb serial

### ISSUE THREAD

**Issue by metehankutlu** [GaudiLabs/OpenThereminV4#13]
I'm trying to connect my v4 through usb serial but I'm not getting any data from the theremin.

<img width="661" alt="Screenshot 2024-01-03 at 12 56 25" src="https://github.com/GaudiLabs/OpenThereminV4/assets/14045288/f52259bf-ee68-43fe-b99f-26c9e9b9eb9f">

I am sure about "/dev/ttyUSB0" because it's the only available port. It's also doesn't show anything when I use ttymidi. What am I doing wrong?

**Comment by MrDham** [comment]
Hello, 

Out of the box, Open Theremin V4 doesn't come with MIDI. 
The serial port is there to monitor calibration and as such is just a serial port. 

If you downloaded the MIDI software into your open theremin V4 and are seeking for some support, then you should rather ask this question in my repo https://github.com/MrDham/OpenTheremin_V4_with_MIDI.

**Comment by metehankutlu** [comment]
Oh it says "OpenTheremin **with MIDI software** is sending MIDI..." I haven't read that correctly. I thought there was something wrong with my theremin, thanks!
