### ISSUE TITLE
PCB file is inconsistent with GBR file.

### ISSUE THREAD

**Issue by ws786873** [GaudiLabs/OpenThereminV4#4]
PCB file is inconsistent with GBR file. I want to use PCB file to generate SMT positioning, but it seems that PCB file is a semi-finished product. 0603 is a little difficult for me.

**Comment by GaudiLabs** [comment]
Hi
Before just accusing me of publishing unfinished files, please tell me who you are and how you can contribute in joining this project. Then please be  specific enough for me to see where you ran into problems. If you just want a working theremin you can buy it here:

gaudishop.ch

Best,
Urs

On 6 March 2022 10:30:15 CET, ws786873 ***@***.***> wrote:
>PCB file is inconsistent with GBR file. I want to use PCB file to generate SMT positioning, but it seems that PCB file is a semi-finished product. 0603 is a little difficult for me.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/GaudiLabs/OpenThereminV4/issues/4
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
🧪 GaudiLabs LLC
Urs Gaudenz
Email: ***@***.***
www.gaudi.ch

**Comment by ws786873** [comment]
Sorry, I just want to make one. I can't seem to contribute anything to the project. Sorry again.

**Comment by GaudiLabs** [comment]
The files are designed on the open design software KiCad. You can export Gerber files from thete. If you see inconsistencies with the repo files,  please regenerate the gerber files and fix that
Urs


On 6 March 2022 11:14:55 CET, ws786873 ***@***.***> wrote:
>Sorry, I just want to make one. I can't seem to contribute anything to the project. Sorry again.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/GaudiLabs/OpenThereminV4/issues/4#issuecomment-1059933237
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
🧪 GaudiLabs LLC
Urs Gaudenz
Email: ***@***.***
www.gaudi.ch
