### ISSUE TITLE
ATmega fuses setting

### ISSUE THREAD

**Issue by roman-dvorak** [GaudiLabs/OpenThereminV4#9]
Hello, 
is known the correct setting of ATmega fuses? It would be useful to describe it somewhere.

Thank you

**Comment by GaudiLabs** [comment]
FUSES

EXTENDED FUSE BYTE (EFUSE):  0xFD
HIGH FUSE BYTE:  0xDE
LOW FUSE BYTE: 0xFF

(Same as Arduino UNO.)
